#!/usr/bin/env php
<?php

date_default_timezone_set('UTC');

set_time_limit(0);

@include_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Database Console Helper', '0.1.1');

foreach (glob(__DIR__ . '/../src/Kos/Commands/*Command.php') as $FileName) {
    $className = "Kos\\Commands\\" . rtrim(basename($FileName), ".php");
    $app->addCommands(array(
        new $className,
    ));
}

$app->run();
